[log]
  level = "DEBUG"
  filePath = "/etc/traefik/log/traefik.log"

[accessLog]
  filePath = "/etc/traefik/log/access.log"
  bufferingSize = 100

[api]
  dashboard = true
  debug = true
  insecure = true

# Entrypoints, http and https
[entryPoints]
  [entryPoints.web]
    address = ":80"
      [entryPoints.web.http]
        [entryPoints.web.http.redirections]
          [entryPoints.web.http.redirections.entryPoint]
            to = "websecure"
            scheme = "https"
  [entryPoints.websecure]
    address = ":20443"

[providers.docker]
    exposedByDefault = false
    endpoint = "unix:///var/run/docker.sock"
